apiVersion: apps/v1
kind: Deployment
metadata:
  name: walmart-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: walmart-app
  template:
    metadata:
      labels:
        app: walmart-app
    spec:
      containers:
        - name: walmart-app
          image: walmart-app:latest
          imagePullPolicy: Never   # Important: use local image, don't pull
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: walmart-service
spec:
  selector:
    app: walmart-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001   # Access via Minikube NodePort
  type: NodePort
